                                                                                                                                                                                                      
 package com.aetrade.paymentbridge.service;                                                                                                                                                                 
                                                                                                                                                                                                            
 import java.time.LocalDateTime;                                                                                                                                                                            
 import java.time.format.DateTimeFormatter;                                                                                                                                                                 
 import java.util.HashMap;                                                                                                                                                                                  
 import java.util.Map;                                                                                                                                                                                      
                                                                                                                                                                                                            
 import org.springframework.beans.factory.annotation.Autowired;                                                                                                                                             
 import org.springframework.stereotype.Service;                                                                                                                                                             
                                                                                                                                                                                                            
 import com.aetrade.paymentbridge.model.PaymentRequest;                                                                                                                                                     
 import com.aetrade.paymentbridge.model.PaymentResponse;                                                                                                                                                    
 import com.aetrade.paymentbridge.model.Transaction;                                                                                                                                                        
 import com.aetrade.paymentbridge.repository.TransactionRepository;                                                                                                                                         
                                                                                                                                                                                                            
 @Service                                                                                                                                                                                                   
 public class VisaPaymentService implements GatewayService {                                                                                                                                                
                                                                                                                                                                                                            
     @Autowired                                                                                                                                                                                             
     private TransactionRepository transactionRepository;                                                                                                                                                   
                                                                                                                                                                                                            
     @Override                                                                                                                                                                                              
     public PaymentResponse processPayment(Map<String, Object> renRequest) {                                                                                                                                
         PaymentResponse response = new PaymentResponse();                                                                                                                                                  
         response.setStatus("APPROVED");                                                                                                                                                                    
         response.setResponseCode("200");                                                                                                                                                                   
         response.setResponseMessage("Visa transaction successful");                                                                                                                                        
         return response;                                                                                                                                                                                   
     }                                                                                                                                                                                                      
                                                                                                                                                                                                            
     @Override                                                                                                                                                                                              
     public void processCallback(PaymentResponse response) {                                                                                                                                                
         // Logic to handle the callback from Visa                                                                                                                                                          
     }                                                                                                                                                                                                      
                                                                                                                                                                                                            
     @Override                                                                                                                                                                                              
     public Map<String, Object> transformToRENFormat(PaymentRequest paymentRequest) {                                                                                                                       
         Map<String, Object> renRequest = new HashMap<>();                                                                                                                                                  
         Map<String, Object> document = new HashMap<>();                                                                                                                                                    
         Map<String, Object> accptrAuthstnReq = new HashMap<>();                                                                                                                                            
         Map<String, Object> hdr = new HashMap<>();                                                                                                                                                         
         Map<String, Object> authstnReq = new HashMap<>();                                                                                                                                                  
         Map<String, Object> envt = new HashMap<>();                                                                                                                                                        
         Map<String, Object> acqrr = new HashMap<>();                                                                                                                                                       
         Map<String, Object> mrchnt = new HashMap<>();                                                                                                                                                      
         Map<String, Object> lctnAndCtct = new HashMap<>();                                                                                                                                                 
         Map<String, Object> pstlAdr = new HashMap<>();                                                                                                                                                     
         Map<String, Object> tx = new HashMap<>();                                                                                                                                                          
         Map<String, Object> txDtls = new HashMap<>();                                                                                                                                                      
         Map<String, Object> txId = new HashMap<>();                                                                                                                                                        
                                                                                                                                                                                                            
         // Header Information                                                                                                                                                                              
         hdr.put("MsgFctn", "AUTQ");                                                                                                                                                                        
         hdr.put("PrtcolVrsn", "2.0");                                                                                                                                                                      
         hdr.put("CreDtTm", LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME));                                                                                                                   
                                                                                                                                                                                                            
         // Environment                                                                                                                                                                                     
         acqrr.put("Id", "configured_acquirer_id");                                                                                                                                                         
         pstlAdr.put("TwnNm", paymentRequest.getBillingAddress().get("city"));                                                                                                                              
         pstlAdr.put("CtryCd", paymentRequest.getBillingAddress().get("country"));                                                                                                                          
         pstlAdr.put("PstCd", paymentRequest.getBillingAddress().get("zip"));                                                                                                                               
         lctnAndCtct.put("PstlAdr", pstlAdr);                                                                                                                                                               
         mrchnt.put("Id", "configured_merchant_id");                                                                                                                                                        
         mrchnt.put("LctnAndCtct", lctnAndCtct);                                                                                                                                                            
         envt.put("Acqrr", acqrr);                                                                                                                                                                          
         envt.put("Mrchnt", mrchnt);                                                                                                                                                                        
                                                                                                                                                                                                            
         // Transaction Details                                                                                                                                                                             
         txDtls.put("TtlAmt", paymentRequest.getAmount());                                                                                                                                                  
         txDtls.put("Ccy", paymentRequest.getCurrency());                                                                                                                                                   
         tx.put("TxDtls", txDtls);                                                                                                                                                                          
         tx.put("TxTp", "CRDP");                                                                                                                                                                            
         txId.put("TxDtTm", LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME));                                                                                                                   
         txId.put("TxRef", paymentRequest.getOrderId());                                                                                                                                                    
         tx.put("TxId", txId);                                                                                                                                                                              
                                                                                                                                                                                                            
         // Assemble the request                                                                                                                                                                            
         authstnReq.put("Envt", envt);                                                                                                                                                                      
         authstnReq.put("Tx", tx);                                                                                                                                                                          
         accptrAuthstnReq.put("Hdr", hdr);                                                                                                                                                                  
         accptrAuthstnReq.put("AuthstnReq", authstnReq);                                                                                                                                                    
         document.put("AccptrAuthstnReq", accptrAuthstnReq);                                                                                                                                                
         renRequest.put("Document", document);                                                                                                                                                              
                                                                                                                                                                                                            
         return renRequest;                                                                                                                                                                                 
     }                                                                                                                                                                                                      
                                                                                                                                                                                                            
     @Override                                                                                                                                                                                              
     public void saveTransaction(PaymentRequest paymentRequest, PaymentResponse paymentResponse) {                                                                                                          
         Transaction transaction = new Transaction();                                                                                                                                                       
         transaction.setTransactionReference(paymentRequest.getTransactionReference());                                                                                                                     
         transaction.setAmount(paymentRequest.getAmount());                                                                                                                                                 
         transaction.setCurrency(paymentRequest.getCurrency());                                                                                                                                             
         transaction.setPaymentMethod(paymentRequest.getPaymentMethod());                                                                                                                                   
         transaction.setCustomerId(paymentRequest.getCustomerId());                                                                                                                                         
         transaction.setStatus(paymentResponse.getStatus());                                                                                                                                                
         transaction.setResponseCode(paymentResponse.getResponseCode());                                                                                                                                    
         transaction.setResponseMessage(paymentResponse.getResponseMessage());                                                                                                                              
         transactionRepository.save(transaction);                                                                                                                                                           
     }                                                                                                                                                                                                      
 }   